infra:
  type: ec2
  instance_type: t2.micro
  ami_image: ami-0889a44b331db0194
image:
  type: docker
  base: python:3.10.8-slim-bullseye
  registry: dockerhub  # this section is optional! if not specified, we use ECR
  registry_creds:  # also optional!
    username:
    password: