name: mypy and flake8

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r style_requirements.txt
    - name: mypy
      run: |
        mypy   alto/agents/ alto/parsers/ alto/tasks/ alto/constants.py alto/entrypoints.py alto/main.py alto/alto_logger.py alto/ui.py alto/utils.py
        flake8 alto/agents/ alto/parsers/ alto/tasks/ alto/constants.py alto/entrypoints.py alto/main.py alto/alto_logger.py alto/ui.py alto/utils.py
