name: mypy and flake8

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r style_requirements.txt
    - name: mypy
      run: |
        mypy   nomad/agents/ nomad/parsers/ nomad/mixins/ nomad/tasks/ nomad/constants.py nomad/entrypoints.py nomad/main.py nomad/nomad_logger.py nomad/ui.py nomad/utils.py
        flake8 nomad/agents/ nomad/parsers/ nomad/mixins/ nomad/tasks/ nomad/constants.py nomad/entrypoints.py nomad/main.py nomad/nomad_logger.py nomad/ui.py nomad/utils.py
