name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'nomad/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['python3.8', 'python3.9', 'python3.10']
    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r dev_requirements.txt
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        build-args: |
          PYTHON_VERSION=${{ matrix.python-version }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
        tags: nomad-dev-${{ matrix.python-version }}:latest
    
    - name: Unit tests
      run: |
        pytest --ignore=nomad/tests/integration
    
    - name: Integration tests
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker run -v /var/run/docker.sock:/var/run/docker.sock nomad-dev-${{ matrix.python-version }}:latest
